use_frameworks!
platform :ios, '9.0'
pod 'BarcodeScanner', path: '../../'
target 'BarcodeScannerExample'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
